version: '3.4'
services:

  flask:
    container_name: 'addirap'
    build:
      context: .
      dockerfile: dockerfile.flask
    ports:
      - 5000:5000
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: bash -c "python app.py"
